<?php

namespace FL\FlfagBundle\Repository;

/**
 * ChaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChaRepository extends \Doctrine\ORM\EntityRepository
{
}
