<?php

namespace FL\FlfagBundle\Repository;

/**
 * HasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HasRepository extends \Doctrine\ORM\EntityRepository
{
}
