<?php

namespace FL\FlfagBundle\Repository;

/**
 * Post_closeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Post_closeRepository extends \Doctrine\ORM\EntityRepository
{
}
