<?php

namespace FL\FlfagBundle\Repository;

/**
 * StafRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StafRepository extends \Doctrine\ORM\EntityRepository
{
}
